### PR TITLE
SuperCollider language added

### PR DESCRIPTION
**Pull request by pwqw**
Added links to channel and group about SuperCollider language. [Project site](http://supercollider.github.io/).  
The channels were just created after finding no others anywhere.

### CODE REVIEW

**Comment by stkw0** [comment]
Thanks

**Comment by stkw0** [comment]
I removed the English channel because this is a list of groups, not channels.

**Comment by pwqw** [comment]
Excuse me, was a mistake. Now, the english SuperCollider group is literally a group.

**Comment by stkw0** [comment]
Perfect, I have already reverted my commit.

**Comment by pwqw** [comment]
Thanks a lot!

**Pull request merged**
